version: "3.1"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3366:3306"
    volumes:
      - highshool-data:/var/lib/mysql

volumes:
  highshool-data: