spring:
  datasource:
    url: jdbc:mysql://localhost:3306/high_school?useSSL=false&createDatabaseIfNotExists=true
    username: root
    password: Bruno22
  jpa:
    hibernate:
      ddl-auto: update

